### PR TITLE
v2.12

### PR DESCRIPTION
**Pull request by robkspeer**
* Adds support for token-based authentication when syncing feature
edits.
* Reduces POST request payload size when syncing edits by removing the
InfoTemplate from request parameters.

### CODE REVIEW

**Comment by andygup** [comment]
Looking good! 

Can you also include the new unit tests that you showed me: `oAutho.html` and `TokenBased.html`? Don't forget to scrub the feature service URLs with something like "insert your own OAuth/Token-based feature service URL here" :-)

Just push those to your personal github fork on branch v2.12. The PR will automatically include them.

Below is a snapshot of all the files included in the PR. You can see the same thing by clicking [here](https://github.com/Esri/offline-editor-js/pull/387/files?diff=unified&short_path=4ac32a7) > then click click the '12 changed files' hyperlink: 

image

**Comment by robkspeer** [comment]
Just added:
test/SpecRunner.offlineFeaturesManager.TokenBased.html
and
test/SpecRunner.offlineFeaturesManager.oAutho.html

there are minimal changes to your own offlineFeatureManager test in these.  Just adding esri/IdentityManager and esri/arcgis/OAuthInfo modules, to allow logging into secured services for token testing, and the AGOL platform to test oAuth, respectively.  Also just added the minimum amount of code, markup, and styles to get them working.  Added the comments as you suggested.  Just also have to be sure to change the URLs in your test/spec/offlineFeaturesManagerSpec.js when running these too!

**Comment by andygup** [comment]
Hey Rob,

Thanks again for the pull request! I’ve merged it in.

I have a quick-hit bug fix to push out today or tomorrow. Do you want to do the gh-pages merge and create a release entry<https://github.com/Esri/offline-editor-js/releases> for the experience, or do you want me to simply roll it all into v2.12.1?

Let me know,

-Andy

**Comment by robkspeer** [comment]
I may have one more change to make, so I should probably just role it in now too.

In regards to deleting the infoTemplate portion before making the `offlineFeatureManager._makeEditRequest`, you were right of course about the POST size limit not being an issue.  The issue turns out to be that an infoTemplate that contains HTML can escape out the valid JSON of the request parameters, and will return a `"No edits ('adds', 'updates' or 'deletes') were specified"` error.

This is also true when apply an Add, so I need to add in to delete the infoTemplate object from the "add" parameter as well as the "update" parameter.

The other option would be to do a `u = "&updates=" + encodeURIComponent(JSON.stringify(updates))` in order to submit the JSON successfully, but it seems removing it entirely and making the request lighter weight may be a better since the infoTemplate doesn't effect the edit.

**Comment by andygup** [comment]
I agree, it's best to leave the infoTemplate out completely and not pass the unused extra bytes via the HTTP request. 

Just a quick note: If you have additional changes, it will need to be a new release number and I'd even suggest opening a new issue. This pull request is already merged and done.

**Pull request merged**
