### PR TITLE
append token to applyEdits request

### PR DESCRIPTION
**Pull request by robkspeer**
For use with secured services and token based security, made changes when making the applyEdits request to the REST endpoint in offline-edit-src.

Delete infoTemplates from update features to reduce request size.

If there are tokens stored in the kernel, and the token is for the feature's hosting server, append the token to the request parameters.

### CODE REVIEW

**Comment by andygup** [comment]
Hey Rob, nice job, thanks for the PR! 

I have a few comments that we'll need to work thru before merging this in. 

>>Delete infoTemplates from update features to reduce request size.

Very minor documentation issue. I see your code comment about 2048 character size limit. I like the idea of reducing the request size, that's excellent. I suggest modifying the comment to only say it's to decrease payload size, and remove the reference 2048 characters. I'm fairly certain that `applyEdits()` and `_makeEditRequest()` both use POST so the 2048 limit in theory shouldn't apply.

**The build process**

I haven't ever really documented all the steps for doing a build, so here they are for the first time. I should create a wiki for this anyway so I'm glad I'm finally writing it all down:

* The changes you made in the PR aren't in the correct location. They are in final, concatenated distribution version of the source. They'll need to be re-written to their respective, original source files under the `/lib` directory, and then the final distribution source files can be magically rebuilt. 
* The build number needs to be incremented in the `/offline-editor-js/package.json` and `/offline-editor-js/samples/package.json` files. On the surface this looks like it may be v2.12.0. Make sure you include the final dot-zero, or whatever the appropriately number is for the patch version, so that Node.js doesn't throw a compilation error.
* `CHANGELOG.md` file needs to be update.
* Any related documentation (How-to or API doc) needs to be manually updated for now. In v3.0 of the repo I hope to enable the ability to create the docs automatically from code comments.
* Write unit tests to validate any new functionality. In this case validate that the library works against a secure public service and make sure that this also doesn't break the OAuth authentication pass-thru. On a related note, currently the unit tests are written in Jasmine and they run separately from the build process. They all live under `/offline-editor-js/tests/` and are manually (I know...old school) run in a browser window.
* To do the build, the `grunt build` command runs a process that does all the heavy lifting for you. It runs jshint, jslint, and concatenates the `src` files in the correct order. Next, it creates the `min` files and then creates (or overwites if the files already exist) all the final source and minified files under `/dist`. 
* For major and minor releases (e.g. v2.0 and v2.1, respectively), merge gh-pages on the local fork, push to the remote fork in your personal github repo, and then create a PR to the official `https://github.com/Esri/offline-editor-js/gh-pages` branch. I have a TO-DO note to automate this step in the future.
* Create a new [release package](https://github.com/Esri/offline-editor-js/releases) for major and minor releases. Patch releases that only include minor, non-critical path documentation updates don't need an associated `release`.
* Whew, that should do it! It sounds like a lot but it goes quickly for minor updates.

Let me know if these steps are something you have time and interest in tackling? I'm more than happy to help walk you thru it!

**Comment by robkspeer** [comment]
great!

thanks Andy!!

I'll get to work on the build process and if I have any issues I will be in contact.

-rob.

**Comment by andygup** [comment]
How are things looking? I have a few non-code change updates that I might push out later this week. If that occurs you should be able to a do a simple merge without any conflict resolution.

**Comment by robkspeer** [comment]
For now I've closed out the pull request.  I worked thru the build process, but I don't have a secure service that I can make public to unit test with your offlineFeatureManagerSpec.  Are you aware of a secured FeatureServer I could test with on an Esri sample server, particularly knowing any existing features will first be deleted when running the test?  And while I don't use oAuth and don't personally plan on it, I am guessing we need a public/secured hosted feature service on ArcGIS.com to test against also?

I'm happy to configure new tests so we can add this functionality, but I can't dedicate a test service that I can share credentials for on any of my servers or arcgis.com organizations.

Thanks for any suggestions,

**Comment by andygup** [comment]
Gotcha. Yep, I can easily drum up an empty service that we can use privately for testing on an AGOL org account.

Do you wanna send me an email address I can use to add you to that private org? My email is: agup at esri.

**Pull request closed without merging**
