### PR TITLE
v3.0.6 3/3/2016

### LINKED ISSUE #448: OfflineEditAdvanced - after multiple offline restarts, UID begins at -1 again for Adds
Hi Andy, I noticed that after an offline restart, and recreating features from ```offlineFeatureManager.getFeatureLayerJSONDataStore(success,dataStore){...}```, the dataStore correctly populates the OIDs of any features created in the first offline-loaded session with their respective temporary negative numbers.

But on subsequent offline restarts, when creating another new feature, the features created in the new session will start over at -1, which then performs an Update on the previously assigned OID-1, instead of an Add of a new feature with OID -2.

Perhaps I'm just missing something -- Is there a way to point the offline Feature Layer to the existing OIDs of recreated features, so that the OfflineEditAdvanced correctly picks up where the previous session left off?

Thanks,
-rob.

### PR DESCRIPTION
**Pull request by robkspeer**
## Version 3.0.6 - March 3, 2016

No breaking changes

**Bug Fixes**

* Closes #448 - OfflineEditAdvanced - after multiple offline restarts,
UID begins at -1 again for Adds.

### CODE REVIEW

**Comment by andygup** [comment]
Did you get the `preserveComments` figured out? My guess was it might be a `grunt-contrib-uglify` version issue. I'm running 0.9.2 locally (`npm list grunt-contrib-uglify`)

Lemme know when it's stable, and I'll take a look at the core changes?

**Comment by robkspeer** [comment]
npm installed grunt-contrib-uglify v0.11.1 for me, altho the [uglify docs](https://github.com/gruntjs/grunt-contrib-uglify#preservecomments) still show that 'some' should have gotten rid of the ```//``` and ```/* */``` comments??  I don't know what was up.. I also haven't used that option before so I can't really say.

PR #450 does have the core changes in place for ```lib/edit/editsStore.js```, ```lib/edit/OfflineEditAdvanced.js```, and ```lib/edit/OfflineEditBasic.js``` if you want to check those out.  The build was good otherwise except for that comment issue I believe.

**Comment by andygup** [comment]
Nice job, btw!

Yep, there have been grumblings that the latest versions have breaking changes to the way comments used to work, and that the changes weren't well documented. I'll bump up my uglify version and take a look.

I'll also take a look at core tomorrow.

**Comment by andygup** [comment]
RE: uglify and comments not working correctly https://github.com/gruntjs/grunt-contrib-uglify/issues/366

**Pull request closed without merging**
